### ISSUE TITLE
Support Ollama

### ISSUE THREAD

**Issue by zhqfdn** [yeokm1/doschgpt#10]
Can we increase support for Ollama servers?

**Comment by yeokm1** [comment]
Hi, I have other commitments so I won't be adding new features at this time. I'm however open to review pull requests.

**Comment by yeokm1** [comment]
Looking into this.

**Comment by yeokm1** [comment]
Support added in latest v0.18 release. Do give it a try. :)

https://github.com/yeokm1/doschgpt/releases/tag/v0.18
