### ISSUE TITLE
DOSBox Support?

### ISSUE THREAD

**Issue by OpenRift412** [yeokm1/doschgpt#4]
Is there a way to get this client connected to ChatGPT in DOSBox? If so, would that require a specific fork of DOSBox or could it be done via IPX tunnelling?

**Comment by yeokm1** [comment]
The application requires a packet driver to be loaded and MTCP to configure the DHCP. I have not used DOSBox for testing. However based on my research and understanding, the version of DOSBOX that has this NE2000 is a patched version.

You may be able to use DOSBOX-X but I have not tried that. https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X
