### ISSUE TITLE
Cannot find content

### ISSUE THREAD

**Issue by Q1984** [yeokm1/doschgpt#6]
Hello,

What should be the problem?

![kép](https://user-images.githubusercontent.com/50952023/228787548-6a950057-76cb-471f-b827-8606f704db6e.png)

![kép](https://user-images.githubusercontent.com/50952023/228787621-fe7bd361-ef61-45ac-b1ad-1d1ce9221ae6.png)

**Comment by yeokm1** [comment]
Hi

I will need more information like
* Machine type
* CPU type
* DOS version
* Network adapter/Packet Driver Type
What system is the proxy running on too?

Also can you run the binary with the `-drr` argument? This should give me some information what is being received by the client.

**Comment by Q1984** [comment]
Virtualbox machine with freeDOS .1.3

![kép](https://user-images.githubusercontent.com/50952023/228815319-9d7606cb-72b6-4cd8-a187-97cf40fbbe6c.png)

**Comment by yeokm1** [comment]
Hi

I have replicated a FreeDOS 1.3 setup on my Virtualbox. All seems good for me.

![image](https://user-images.githubusercontent.com/1570592/228829247-19270de0-d885-43ea-81a6-961552bb977a.png)
![image](https://user-images.githubusercontent.com/1570592/228827752-d6dc8e2a-39f2-44f4-b9ad-aab015428362.png)
![image](https://user-images.githubusercontent.com/1570592/228828073-ec252724-7fd1-4850-bac5-5bb0a0d19b62.png)
![image](https://user-images.githubusercontent.com/1570592/228828315-fb5b2a8e-0706-460a-bf93-27115056dc46.png)

May I know more your network configuration setup? Are you behind some form of firewall or another proxy? 
Also are you using and custom command line arguments for the http-to-https proxy?

This seems like a proxy problem to me. What is the setup of the proxy?

**Comment by Q1984** [comment]
I' ve figured out finally.
Bridged network must be used in VB any other modes not work. For example NAT. It seems working, can download with wget but it is not enough in this case.

![kép](https://user-images.githubusercontent.com/50952023/228923122-bc41e44f-ec46-4e5e-a181-ff96b59d222e.png)

**Comment by yeokm1** [comment]
I have a hunch where this problem may be coming from but I have to replicate first. May I know what type of host system are you using, Windows/Mac/Linux and which version?

Also, is the proxy running on the same host system?

**Comment by Maillouski** [comment]
> I' ve figured out finally. Bridged network must be used in VB any other modes not work. For example NAT. It seems working, can download with wget but it is not enough in this case.
> 
> ![kép](https://user-images.githubusercontent.com/50952023/228923122-bc41e44f-ec46-4e5e-a181-ff96b59d222e.png)

This looks like a firewall/routing issue you have internally though.

**Comment by yeokm1** [comment]
Should reduce the incidence of this in latest releases https://github.com/yeokm1/doschgpt/releases

Further wait for 200ms after the last non-zero byte receive to be sure there are no more bytes incoming from the socket

**Comment by Q1984** [comment]
With the latest release it works behind nat in VB as well. ;)

**Comment by yeokm1** [comment]
@Q1984 Thanks for reporting this issue! 👍
