### ISSUE TITLE
Unable to use double quotes in string

### ISSUE THREAD

**Issue by Maillouski** [yeokm1/doschgpt#7]
Writing anything with double quotes results in the API saying the JSON payload is broken.

Example:

Me:
Say "hello world"

this will break the JSON payload.

**Comment by yeokm1** [comment]
I can replicate this issue. Yeah, let me look into escaping the illegal characters.

**Comment by yeokm1** [comment]
In progress
![image](https://user-images.githubusercontent.com/1570592/229147919-0080f9db-5bf3-4494-aa09-1b0cf143d47d.png)

**Comment by yeokm1** [comment]
Solved in latest releases https://github.com/yeokm1/doschgpt/releases
