### ISSUE TITLE
Convert special characters, like accents to the right ASCII char code

### ISSUE THREAD

**Issue by Maillouski** [yeokm1/doschgpt#8]
For example, the letter "é" should be converted to char 130(dec). Right now we get somekind of garbage.

**Comment by yeokm1** [comment]
Hmm... That's not a standard ASCII character. I'm not sure if DOS systems can print such an Extended ASCII character but I can check. It could be doable.

If you don't mind, can you send me the prompt you gave to ChatGPT to generate an output that has this character? Including screenshots of the garbage and the raw JSON output that has this issue.

**Comment by Maillouski** [comment]
![image](https://user-images.githubusercontent.com/26332223/229009349-e4d04517-b4e3-42c8-84d6-5df57e718481.png)

**Comment by Maillouski** [comment]
DOS can print those chars.
You can check the extended ASCII table using CP437 (MS-DOS default encoding) here :
https://www.rapidtables.com/code/text/ascii-table.html

**Comment by yeokm1** [comment]
Can I check if the expected output is supposed to be the following?
```text
J'ai attribué
Tu as attribué
Il/Elle a attribué
Nous avons attribué
Vous avez attribué
Ils/Elles ont attribué
```
For "Il/Elle" and "Ils/Elles", are those actually printed in the correct way?

**Comment by Maillouski** [comment]
This output is 100% correct

**Comment by yeokm1** [comment]
In progress

![image](https://user-images.githubusercontent.com/1570592/229146087-d9f9e8ed-e188-452e-ab5e-87d257eaaed5.png)

**Comment by yeokm1** [comment]
Solved in latest releases https://github.com/yeokm1/doschgpt/releases by converting from Unicode to Code Page 437
